### ISSUE TITLE
Infinite loop comparing recursive types (such as Type)

### ISSUE THREAD

**Issue by ddssff** [mgsloan/th-orphans#13]
ghci
    > :set -XTemplateHaskell
    >  :m +Language.Haskell.TH Language.Haskell.TH.Instances
    > compare (AppT (ConT ''Maybe) (ConT ''Int)) (ConT ''Char)

I am suspicous of this line: https://github.com/mgsloan/th-orphans/blob/master/src/Language/Haskell/TH/Instances/Internal.hs#L37.  I think what needs to happen there is for the names of the two expression's constructors to be compared.

**Comment by mgsloan** [comment]
Wow, good catch, I'm not sure why I haven't encountered issues like this before!

I've pushed a fix: https://github.com/mgsloan/th-orphans/commit/ced500c117b0a7222a1ca41d52aa59c7c8a81919

Looks like it already generated a data-type specialized version of `constrIndex`, but didn't use it for some strange reason..  Not that it matters much, but I didn't write this code - it came from http://hackage.haskell.org/package/haskell-src-meta

**Comment by mgsloan** [comment]
@ddssff Can you confirm that this resolves the issue?

**Comment by ddssff** [comment]
Yes, it does.
