### ISSUE TITLE
`th-orphans` fails to compile with GHC 7.[02]

### ISSUE THREAD

**Issue by hvr** [mgsloan/th-orphans#20]
As you can see on

https://ghc.haskell.org/~hvr/buildreports/th-orphans.html

`th-orphans-0.11.0` fails to compile with GHC 7.0, causing a `cabal install th-orphans` to fail rather than fall-back to `th-orphans-0.9.1` which still worked.

Was dropping support for GHC 7.0 deliberate? if so, the  lower bound on `base` needs to be updated (to e.g. `base >= 4.5`).

**Comment by mgsloan** [comment]
Thanks for reporting this, @hvr, and thanks for fixing it, @ddssff!  [th-orphans-0.11.1](http://hackage.haskell.org/package/th-orphans-0.11.1) is now on hackage.
