### ISSUE TITLE
Compilation problem using GHC 7.4.1

### ISSUE THREAD

**Issue by HounD** [mgsloan/th-orphans#7]
If you are need extra info, pease contact me.

The output of cabal install was:
>Resolving dependencies...
>Configuring th-orphans-0.8...
>Building th-orphans-0.8...
>Preprocessing library th-orphans-0.8...
>[1 of 1] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell>/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.o )
>Loading package ghc-prim ... linking ... done.
>Loading package integer-gmp ... linking ... done.
>Loading package base ... linking ... done.
>Loading package array-0.4.0.0 ... linking ... done.
>Loading package deepseq-1.3.0.0 ... linking ... done.
>Loading package containers-0.4.2.1 ... linking ... done.
>Loading package pretty-1.0.1.2 ... linking ... done.
>Loading package template-haskell ... linking ... done.
>Loading package th-lift-0.5.5 ... linking ... done.
>
>src/Language/Haskell/TH/Instances.hs:101:3:Failed to install th-orphans-0.8
>cabal: Error: some packages failed to install:
>th-orphans-0.8 failed during the building phase. The exception was:
>ExitFailure 139

**Comment by mgsloan** [comment]
Closing this as it's an old issue.  Reopen if it's still a problem!
